Ovevřeni souboru s ruiany

In [3]:
import pandas as pd

df = pd.read_csv('dpd_getAll_country203_kod_obce.csv')

df.head(5)

,id,company,street,city,country_id,house_number,postcode,phone,fax,email,...,open_weekend,latitude,longitude,hours,photo,kod_adresy,search_type,search_term,search_matches_cnt,kod_obce
0,CZ10037,Teleric Elektro,Pražská,Brandýs Nad Labem,203,67/3,25001,225373373,NaN,info@dpd.cz,...,1,50.184980,14.659560,"[{'day': 1, 'dayName': 'Pondělí', 'openMorning...",NaN,14608618.0,full_address,Pražská 67/3 Brandýs Nad Labem 25001,1.0,538094.0
1,CZ10046,Elektro-styl.cz,Radlická,Praha,203,1167/17,15000,225373373,NaN,info@dpd.cz,...,0,50.062314,14.404054,"[{'day': 1, 'dayName': 'Pondělí', 'openMorning...",NaN,22086986.0,full_address,Radlická 1167/17 Praha 15000,1.0,554782.0
2,CZ10075,FUXTEC - zahradni technika,Nádražní,Sedlčany,203,906,26401,225373373,NaN,info@dpd.cz,...,0,49.656350,14.432210,"[{'day': 1, 'dayName': 'Pondělí', 'openMorning...",NaN,23042061.0,full_address,Nádražní 906 Sedlčany 26401,1.0,541281.0
3,CZ10084,Fedák Elektro,Malé Náměstí,Rokycany,203,121,33701,225373373,NaN,info@dpd.cz,...,1,49.741580,13.597470,"[{'day': 1, 'dayName': 'Pondělí', 'openMorning...",NaN,26702819.0,full_address,Malé Náměstí 121 Rokycany 33701,1.0,559717.0
4,CZ10090,Elektro OK1,Náměstí Míru,Svitavy,203,196/79,56802,225373373,NaN,info@dpd.cz,...,1,49.755830,16.467440,"[{'day': 1, 'dayName': 'Pondělí', 'openMorning...",NaN,18916368.0,full_address,Náměstí Míru 196/79 Svitavy 56802,1.0,577731.0

In [5]:
df.columns

Index(['id', 'company', 'street', 'city', 'country_id', 'house_number',
       'postcode', 'phone', 'fax', 'email', 'homepage', 'pickup_network_type',
       'pickup_allowed', 'return_allowed', 'dropoff_allowed',
       'express_allowed', 'cardpayment_allowed', 'cod_allowed', 'service',
       'open_weekend', 'latitude', 'longitude', 'hours', 'photo', 'kod_adresy',
       'search_type', 'search_term', 'search_matches_cnt', 'kod_obce'],
      dtype='object')

kontrola sloupců a vyběr jen pár potřebných

In [6]:
vybrane_sloupce = ['company', 'kod_obce', 'city', 'postcode', 'street', 'house_number', 'latitude', 'longitude' ]
df_vybrany = df[vybrane_sloupce]

In [7]:
df_vybrany.head(5)

,company,kod_obce,city,postcode,street,house_number,latitude,longitude
0,Teleric Elektro,538094.0,Brandýs Nad Labem,25001,Pražská,67/3,50.184980,14.659560
1,Elektro-styl.cz,554782.0,Praha,15000,Radlická,1167/17,50.062314,14.404054
2,FUXTEC - zahradni technika,541281.0,Sedlčany,26401,Nádražní,906,49.656350,14.432210
3,Fedák Elektro,559717.0,Rokycany,33701,Malé Náměstí,121,49.741580,13.597470
4,Elektro OK1,577731.0,Svitavy,56802,Náměstí Míru,196/79,49.755830,16.467440

Přejmenování souborů

In [8]:
nove_nazvy_sloupcu = {'company': 'name',
                      'kod_obce': 'city_code',
                      'city': 'city',
                      'postcode':'zip_code',
                      'street': 'street',
                      'house_number': 'house_NO',
                      'latitude': 'latitude',
                      'longitude' :'longitude' 
                      }
df_prejmenovany = df_vybrany.rename(columns = nove_nazvy_sloupcu)

In [9]:
df_prejmenovany.head(5)

,name,city_code,city,zip_code,street,house_NO,latitude,longitude
0,Teleric Elektro,538094.0,Brandýs Nad Labem,25001,Pražská,67/3,50.184980,14.659560
1,Elektro-styl.cz,554782.0,Praha,15000,Radlická,1167/17,50.062314,14.404054
2,FUXTEC - zahradni technika,541281.0,Sedlčany,26401,Nádražní,906,49.656350,14.432210
3,Fedák Elektro,559717.0,Rokycany,33701,Malé Náměstí,121,49.741580,13.597470
4,Elektro OK1,577731.0,Svitavy,56802,Náměstí Míru,196/79,49.755830,16.467440

uložení do noveho csv

In [10]:
df_prejmenovany.to_csv('clean_data_dpd.csv', index=False, encoding='utf-8')